site_name: Introductory Python
site_url: https://ephsmith.github.io/python-book/
nav:
    - Home: index.md
    - Book:
      - 'Chapter 01': 'chapter-01.md'
      - 'Chapter 02': 'chapter-02.md'
    - About: about.md
